#############################################################################
# Makefile for building: Pocket-ImAT
# Generated by qmake (2.01a) (Qt 4.7.2) on: Wed Feb 6 21:30:26 2013
# Project:  Pocket-ImAT.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Pocket-ImAT.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		cena.cpp \
		myview.cpp \
		drawable.cpp \
		circledline.cpp \
		normalline.cpp \
		graphicspixmapitem.cpp \
		scaleline.cpp \
		about.cpp moc_mainwindow.cpp \
		moc_cena.cpp \
		moc_myview.cpp \
		moc_about.cpp
OBJECTS       = main.o \
		mainwindow.o \
		cena.o \
		myview.o \
		drawable.o \
		circledline.o \
		normalline.o \
		graphicspixmapitem.o \
		scaleline.o \
		about.o \
		moc_mainwindow.o \
		moc_cena.o \
		moc_myview.o \
		moc_about.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Pocket-ImAT.pro
QMAKE_TARGET  = Pocket-ImAT
DESTDIR       = 
TARGET        = Pocket-ImAT

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pocket-ImAT.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile Pocket-ImAT.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Pocket-ImAT.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Pocket-ImAT1.0.0 || $(MKDIR) .tmp/Pocket-ImAT1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Pocket-ImAT1.0.0/ && $(COPY_FILE) --parents mainwindow.h cena.h myview.h drawable.h circledline.h normalline.h graphicspixmapitem.h scaleline.h about.h .tmp/Pocket-ImAT1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp cena.cpp myview.cpp drawable.cpp circledline.cpp normalline.cpp graphicspixmapitem.cpp scaleline.cpp about.cpp .tmp/Pocket-ImAT1.0.0/ && $(COPY_FILE) --parents mainwindow.ui about.ui .tmp/Pocket-ImAT1.0.0/ && (cd `dirname .tmp/Pocket-ImAT1.0.0` && $(TAR) Pocket-ImAT1.0.0.tar Pocket-ImAT1.0.0 && $(COMPRESS) Pocket-ImAT1.0.0.tar) && $(MOVE) `dirname .tmp/Pocket-ImAT1.0.0`/Pocket-ImAT1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Pocket-ImAT1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cena.cpp moc_myview.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cena.cpp moc_myview.cpp moc_about.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_cena.cpp: drawable.h \
		cena.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cena.h -o moc_cena.cpp

moc_myview.cpp: myview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) myview.h -o moc_myview.cpp

moc_about.cpp: about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_about.h
ui_mainwindow.h: mainwindow.ui \
		myview.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_about.h: about.ui
	/usr/bin/uic-qt4 about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		cena.h \
		drawable.h \
		myview.h \
		graphicspixmapitem.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

cena.o: cena.cpp cena.h \
		drawable.h \
		circledline.h \
		normalline.h \
		graphicspixmapitem.h \
		scaleline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cena.o cena.cpp

myview.o: myview.cpp myview.h \
		cena.h \
		drawable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myview.o myview.cpp

drawable.o: drawable.cpp drawable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawable.o drawable.cpp

circledline.o: circledline.cpp circledline.h \
		drawable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o circledline.o circledline.cpp

normalline.o: normalline.cpp normalline.h \
		drawable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normalline.o normalline.cpp

graphicspixmapitem.o: graphicspixmapitem.cpp graphicspixmapitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicspixmapitem.o graphicspixmapitem.cpp

scaleline.o: scaleline.cpp scaleline.h \
		normalline.h \
		drawable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scaleline.o scaleline.cpp

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cena.o: moc_cena.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cena.o moc_cena.cpp

moc_myview.o: moc_myview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myview.o moc_myview.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

